### ISSUE TITLE
add mypy support (annotations)

### ISSUE THREAD

**Issue by MarcelWilson** [rbarrois/python-semanticversion#152] opened 2023-10-12 20:53 UTC
It would be great if the package had annotations along with a `py.typed` file to allow type checkers (i.e. mypy) the ability to validate.

**Comment by cblegare** [comment] 2023-11-04 00:45
Looks like a duplicate of https://github.com/rbarrois/python-semanticversion/issues/138

**Closed as not planned** 2024-03-19 18:42 UTC
