### ISSUE TITLE
Version bump to 2.7.0 does not adhere to Strict SemVer 2.0

### ISSUE THREAD

**Issue by dnathe4th** [rbarrois/python-semanticversion#78] opened 2019-08-29 00:41 UTC
The [new constructor](https://github.com/rbarrois/python-semanticversion/blob/1655f9cdd72dd3e6dcaf071e84aa5e897e06d39d/semantic_version/base.py#L87) leveraging Python3 syntax is a breaking change and should result in a major version bump to 3.0 per SemVer2.0

**Comment by rbarrois** [comment] 2019-08-29 08:32
I'm not totally sure about this: should a version be bumped when one of its dependencies change? :wink:

However, if the issue is the loss of Python2 support, I would happily accept an external contribution to add that back in (only for the 2.x series).

**Comment by rbarrois** [comment] 2019-08-29 09:41
This has been fixed in release 2.8.0; let me know if that's good ;)

**Closed by rbarrois** 2019-08-29 09:41 UTC

**Comment by dnathe4th** [comment] 2019-08-29 19:32
Thank you very much! You raise a great question. I would argue the addition of the bare asterisk is a breaking change even for anyone using python3 already because constructing a `Version` object now must be done with keyword arguments. It just happens to be that my complaint was py2 vs py3 related.
