### ISSUE TITLE
Comparison is broken for partials

### ISSUE THREAD

**Issue by cattz** [rbarrois/python-semanticversion#14] opened 2014-11-05 13:41 UTC
I'm getting wrong results comparing versions using partials :

````python
print semantic_version.Version('1.2.0-beta', partial=True) >  semantic_version.Version('1.2.0', partial=True)
print semantic_version.Version('1.2.0-beta', partial=True) <  semantic_version.Version('1.2.0', partial=True)
print semantic_version.Version('1.2.0-beta', partial=True) == semantic_version.Version('1.2.0', partial=True)

print semantic_version.Version('1.2-beta', partial=True) >  semantic_version.Version('1.2', partial=True)
print semantic_version.Version('1.2-beta', partial=True) <  semantic_version.Version('1.2', partial=True)
print semantic_version.Version('1.2-beta', partial=True) == semantic_version.Version('1.2', partial=True)

print semantic_version.Version('1.2.0-beta') >  semantic_version.Version('1.2.0')
print semantic_version.Version('1.2.0-beta') <  semantic_version.Version('1.2.0')
print semantic_version.Version('1.2.0-beta') == semantic_version.Version('1.2.0')

False
False
True

False
False
True

False
True
False
````

**Comment by rbarrois** [comment] 2015-02-18 21:15
Well, the problem is that ``partial=True`` versions are mostly meant to be used in ``Spec`` objects.
There is a small section describing the behavior in the docs [1], but basically comparing "partials" will only compare defined fields; if the build identifier isn't provided, it is skipped altogether in comparisons.

Could you describe the use-case you have for partials? 

[1] http://python-semanticversion.readthedocs.org/en/latest/reference.html#semantic_version.Version.__cmp__

**Comment by rbarrois** [comment] 2015-09-15 21:52
Without a use case for partials outside ``Spec`` objects, I'm going to close this issue.

Feel free to reopen it if it's still a problem for you!

**Closed by rbarrois** 2015-09-15 21:52 UTC
